### ISSUE TITLE
Cordova-plugin-compat Installation problem

### ISSUE THREAD

**Issue by Dhanasekaranjones** [guyromb/Cordova-open-native-settings#16]
I have install the cordova-plugin-compat@1.1.0 at command promt

And cordova-plugin-compat@1.1.0 installed after not installing the cordova-plugin-camera

I have seen the error for,
```
E:\XCCLive>cordova plugin add cordova-plugin-camera
Installing "cordova-plugin-camera" for android
Failed to install 'cordova-plugin-camera': CordovaError: Version of installed pl
ugin: "cordova-plugin-compat@1.0.0" does not satisfy dependency plugin requireme
nt "cordova-plugin-compat@^1.1.0". Try --force to use installed plugin as depend
ency.
    at C:\Users\administrator.WBCDNS.000\AppData\Roaming\npm\node_modules\cordov
a\node_modules\cordova-lib\src\plugman\install.js:581:33
    at _fulfilled (C:\Users\administrator.WBCDNS.000\AppData\Roaming\npm\node_mo
dules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\administrator.WBCDNS.000\AppData\Roam
ing\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\administrator.WBCDNS.000\AppDat
a\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\administrator.WBCDNS.000\AppData\Roaming\npm\node_modules\cordov
a\node_modules\q\q.js:509:49
    at flush (C:\Users\administrator.WBCDNS.000\AppData\Roaming\npm\node_modules
\cordova\node_modules\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Error: Version of installed plugin: "cordova-plugin-compat@1.0.0" does not satis
fy dependency plugin requirement "cordova-plugin-compat@^1.1.0". Try --force to
use installed plugin as dependency.
```

How to install the **cordova-plugin-compat@1.1.0** & **cordova-plugin-camera** for properly

**Comment by guyromb** [comment]
This issue is not related to this plugin. Try to clean and re-install everything
